version: '2'
services:
  hummingbird-admin:
    image: hummingbird/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  hummingbird-api:
    image: hummingbird/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev